### ISSUE TITLE
Pipe should support && and ||

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/dagr#121]
This `ShellCommand("echo", "-n", "Hello", "&&", "echo", "World")` will produce the following command: `echo -n Hello '&&' echo World`.  I want it to produce `echo -n Hello && echo World`.  Similarly if I use `||`.   Perhaps we extend `Pipe` to support this, or add support directly into `ShellCommand`?

**Comment by tfenne** [comment]
Perhaps I'm being dumb, but how is that different from:
`ShellCommand("echo", "-n", "Hello") ==> ShellCommand("echo", "World")`

We've built a whole pipeline system based around the idea of conditionally executing dependencies when upstream tasks succeed :open_mouth: .  I suspect you have some more complicated thing you're actually trying to do that might be illustrative...

**Comment by nh13** [comment]
I want this (don't hurt me): `ShellCommand("echo", "-n", "Hello", "&&", "exit", "0")`

**Comment by tfenne** [comment]
Now I'm even more confused - `echo`, at least under bash, always exits with `0`.

**Comment by nh13** [comment]
I want `ShellCommand("/please/ignore/me/I/cant/make/this/public/but/it/exits/with/non-zero", "&&", "exit", "0")`.  Please humor me that you can imagine that I don't care about the success of a shell command (or script).

**Comment by nh13** [comment]
Closing since I can do this:
`ShellCommand("/command/that/returns/exit/code/1", "\n", "exit", 0)`
