### ISSUE TITLE
Sonatype release includes all transitive dependencies of picard and htsjdk

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/dagr#127]
Which means that in downstream projects one has to manually add:

```
  ExclusionRule(organization="org.apache.ant"),
  ExclusionRule(organization="gov.nih.nlm.ncbi"),
  ExclusionRule(organization="org.testng"),
  ExclusionRule(organization="com.google.cloud.genomics")
```

in order to not drag in another 20+ jars that cause conflicts but have no utility to dagr.

**Comment by nh13** [comment]
@tfenne I think this is fixed in master: https://github.com/fulcrumgenomics/dagr/blob/master/build.sbt#L164-L169
