### ISSUE TITLE
Documentation organization

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/dagr#19]
Either have it checked in somewhere (say a separate branch) and published somewhere (https://readthedocs.org, or gh-pages).  Nonetheless, as we start to write doc, it needs to go somewhere somehow.

**Comment by tfenne** [comment]
Would be good to also put together an outline for the readme on the main page, so that we can start filling it in.

**Comment by nh13** [comment]
Also a roadmap for features we know about but haven't implemented (ex. persistence).
