### ISSUE TITLE
Badges, badges everywhere

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/dagr#20]
@tfenne as you can see I have embraced badges in our `README.md`.  A good place to go see possible badges is http://shields.io.  I see five possible badges if I were to continue this embrace:
- [x] Build Status - Travis CI - [![Build Status](https://travis-ci.org/fulcrumgenomics/dagr.svg?branch=master)](https://travis-ci.org/fulcrumgenomics/dagr)
- [x] Code Coverage - Codecov - [![Coverage Status](https://img.shields.io/codecov/c/github/fulcrumgenomics/dagr/master.svg)](https://codecov.io/github/fulcrumgenomics/dagr?branch=master)
- [x] Dependency Status - VersionEye - [![Dependency Status](https://www.versioneye.com/user/projects/56b2d2d593b95a003c714340/badge.svg?style=round)](https://www.versioneye.com/user/projects/56b2d2d593b95a003c714340#dialog_dependency_badge)
- [x] Version at Maven Central - example: [![Maven central](https://maven-badges.herokuapp.com/maven-central/com.github.dblock/oshi-core/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.github.dblock/oshi-core)
- [ ] License - [![MIT](http://img.shields.io/badge/license-MIT-blue.svg)](https://www.eclipse.org/legal/epl-v10.html)

Perhaps I am going to far, but I find these types of things useful when visiting a github project page.  What are your thoughts?

**Comment by tfenne** [comment]
I like it!  The only one I'm not 100% keen on is the dependency status, because I'm not really sure how to react to it.  It's telling us that we're not using the latest version of one or more dependencies?  That seems like that will happen quite often.

Might also be nice to have one for implementation/language so it's trivially easy to tell it's scala.

**Comment by nh13** [comment]
I am done with adding badges.  We can see which ones we would like to keep as we move forward.
