### ISSUE TITLE
Back door paths analysis

### ISSUE THREAD

**Issue by ghost** [fulcrumgenomics/dagr#382]
It seems that DagR cannot identify backdoor paths very well. This is from the DagR official manual:
 
“This essentially implements the graphical algorithm described in Greenland (1999) to identify open "backdoor" (or not strictly backdoor, but potentially biasing) paths in a DAG.”

Does anyone know a tool could do the backdoor paths more accurately?

**Comment by nh13** [comment]
I think you have the wrong repository. We have no mention of backdoor paths in our software or documentation.

**Comment by ghost** [comment]
> I think you have the wrong repository. We have no mention of backdoor paths in our software or documentation.

This is what I found and has been using as a tutorial

https://cran.r-project.org/web/packages/dagR/dagR.pdf

if this is the wrong repository, would you mind guiding me to a right one?

**Comment by nh13** [comment]
Fifth hit on google: https://github.com/cran/dagR
Best of luck.

**Comment by ghost** [comment]
> https://github.com/cran/dagR

I went through this link and it has the same thing I post initially about back door paths. See the link follows:

https://github.com/cran/dagR/blob/master/man/eval.paths.Rd

**Comment by nh13** [comment]
Sorry I cannot help you any further as this is a different software. Best of luck.

**Comment by ghost** [comment]
> Sorry I cannot help you any further as this is a different software. Best of luck.

It is okay if you cannot help me further. I appreciate your help.

**But this is the same software (dagR package in R), as I find the introduction in the link you sent me.**

**Comment by nh13** [comment]
It's not search for "fulcrum" in that link.
