### ISSUE TITLE
Consider the idea of a commons package

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/dagr#85]
In the course of another large refactor (https://github.com/fulcrumgenomics/dagr/pull/83), I am convinced that some classes should be in a commons project, in case we want to use them in other repos (such as JeanLuc).  Classes like `StringUtil`, `PathUtil`, and `BiMap` are good candidates.  Lets discuss this possibility. 

Currently, if we want a piece of code accessible to all projects, but not duplicates, we must put it in the project that depends on no other (`sopt`).  I don't think _all_ utility code belongs in `sopt.

@tfenne

**Comment by tfenne** [comment]
I think this makes total sense.  It should probably be it's own repo too if JL and sopt are going to be their own repos long term.  Kind of a hassle while things are evolving rapidly, but not sure what else to do.

**Comment by nh13** [comment]
Done
